### ISSUE TITLE
Host testhost has unknown values

### ISSUE THREAD

**Issue by automate-solutions** [inmanta/drupal#1]
When trying to export the environment, I got the following debug statements:
```
DEBUG    Host testhost has unknown values (in resource std::File[testhost,path=/etc/drupal7/localhost/settings.php])
INFO     Ignoring resource of type openstack::Network because it requested to ignore it. (location: /root/openstack-template/libs/mymodule/model/_init.cf:42)
DEBUG    Host testhost has unknown values (in resource exec::Run[testhost,command=bash -c 'cd /usr/share/drupal7; /usr/bin/drush site-install -y --account-mail=admin@example.com --account-name=admin --account-pass=test --site-name='localhost' --sites-subdir=localhost'])
INFO     The configuration of the following hosts is not exported due to unknown configuration parameters (prune-agent policy):
INFO      - testhost
INFO     Some resources of the following hosts is not exported due to unknown configuration parameters (prune-resource policy):
INFO     Sending resources and handler source to server
```
It is said that there are unknown values but **what are those values** ?
It doesn't specify the module that is impacted (but fortunately, the filenames for which there are some missing arguments are self explanatory).
How can I know what are those unknown values?
I checked in `drupal::Application`, `php::Application` and `web::Application` but I didn't find.
My main.cf is:
```
import ssh
import redhat
import ubuntu
import openstack
import apache
import mysql
import web
import drupal
import mymodule

## Edit this parameters
image_id = "52a7e16f-8d48-4369-af78-2da1d23d2011"
network_name = "private"
subnet_name = "private_subnet"
network_address = "10.0.0.0/24"

flavor_name = "m1.little"
ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7KC7uZ/31S2AfbFZ+3EL5xL29/AF6N5C5oFLDg0qxJwnbLMY9MmU/QbSYG13YkSIyujEGrOqgJH9Q3S6biQ3ibU2RfmXCm0lnWweayz9eKaBbHMF1CqsYnEe6Mt7r2NeOh2uxeJyko+tIeEvOvwC/JZfVV3tBPej0se20SShG/EPHQ2KjWRMMbDBZ57OZ8MT+xmg5qsWobKJHwoIzFYPwlQ07s0Qe7KGBFxBOp5vogZ9Y162Gas7M2/8uz/YfmaL+JIry5Fl88bBtirIZKro7LOq1pDernoqbHnheJo6PAiFzmyEqYVSG5Vlom6F7Gr0Rgmg4BR525q/ilj5sIC7t root@inmanta"

os = redhat::fedora23
## End edit

# register ssh key
ssh_key = ssh::Key(name="mykey", public_key=ssh_public_key)

# create the cluster
cluster = mymodule::MyCluster(network_name=network_name, subnet_name=subnet_name,
                              image_id=image_id, flavor=flavor_name, key=ssh_key,
                              network_address=network_address, os=os)

# make a vm!
host1 = mymodule::MyHost(name="testhost", cluster=cluster)

web_server=apache::Server(host=host1)
mysql_server=mysql::Server(host=host1)

# deploy drupal in that virtual host
name=web::Alias(hostname="localhost")
db=mysql::Database(server=mysql_server, name="drupal_test", user="drupal_test",
                   password="Str0ng-P433w0rd")
drupal::Application(name=name, container=web_server, database=db, admin_user="admin",
                    admin_password="test", admin_email="admin@example.com", site_name="localhost")
```
My project.yml is:
```
name: snippet test
modulepath: [libs,/tmp/inmantalibs]
downloadpath: /tmp/inmantalibs
version: 1.0
repo: ['https://github.com/inmanta/']
```
Thank you for your help

**Comment by bartv** [comment]
This is how we do orchestration. You start a VM on OpenStack which means that initially the orchestrator does not know which ip the virtual machine got.

When you run the server and agent (instead of embedded in the deploy command) this data will become available and will be included in the configuration model. Then the config for the VM becomes available.

The deploy command could do this as well be running it multiple times. However, on Fedora 25 mongodb does not always persists its data when using the deploy command. I have not yet been able to figure out what causes this.

**Comment by automate-solutions** [comment]
So, to clarify the understanding that I have, it is not possible to deploy a machine and install new applications on it in the same environment?
Or do I need to export/deploy twice to have it working?

**Comment by bartv** [comment]
With the current inmanta deploy command it is not possible. You will have to run the server with or without embedded agents.

**Comment by automate-solutions** [comment]
Ok.
Normally, the instance's agent is installed when deployed (through user data).
Isn't possible to force the drupal entity to grab its configuration at runtime? Is there any way to configure my `main.cnf` of the module `mymodule` to force drupal to wait for the instance to be deployed and grab its IP address?
Or to use a `requires` ?

**Comment by bartv** [comment]
You use openstack::Host which creates a virtualmachine resource and a HostPort for eth0. Take a look at https://github.com/inmanta/openstack/blob/master/model/_init.cf#L352 and line 355. 

If you would create a virtual machine with a static ip or create an ip::Host manually such as in the quickstart and set the ip it would work with the deploy command.

The server tracks which data is missing. It queries agents (in this case the iaas agent, NOT the host agent) for this data. When it becomes available the data is stored on the server and if the server has the configuration model it will recompile the model.

This works in theory with the deploy command if you invoke it multiple times:
1) Deploy the vm and register an unknown with the server, but the agent does not yet know the value
2) Recompile the model and now the agent should be able to determine the ip. However, the query mechanism is asynchronous which will result in still having an unknown returned to the compiler but this triggers a query on the agent instead of based on a time out.
3) Recompile and deploy the complete model.

However, at the moment the embedded mongo of the deploy command does not persist data so on every deploy a new environment is created and the unknown are not tracked. This means that the deploy cmd is stuck in step 1.

**Comment by bartv** [comment]
I think this issue can be closed.
